services:
  - type: web
    name: courseSellingApp
    env: node
    plan: free
    region: oregon   # or your preferred region
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
